behaviors:
  SearchTarget:
    trainer_type: ppo
    summary_freq: 10000
    time_horizon: 64
    max_steps: 10000000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 512 
      buffer_size: 10240
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
environment_parameters:
  stage_number:
    curriculum:
      - name: FirstTrain
        completion_criteria:
          measure: reward
          behavior: SearchTarget 
          min_lesson_length: 100
          threshold: 0.999
        value: 1.0
      - name: SecondTrain
        completion_criteria:
          measure: reward
          behavior: SearchTarget 
          min_lesson_length: 100
          threshold: 0.999
        value: 2.0
      - name: ThirdTrain
        completion_criteria:
          measure: reward
          behavior: SearchTarget 
          min_lesson_length: 100
          threshold: 0.98
        value: 3.0
      - name: ForthTrain
        completion_criteria:
          measure: reward
          behavior: SearchTarget 
          min_lesson_length: 100
          threshold: 0.95
        value: 4.0
