behaviors:
  default:
    trainer_type: ppo
    summary_freq: 10000
    time_horizon: 64
    max_steps: 1500000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 512 
      buffer_size: 10240
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
